# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('wall', 'Wall display (always on)'), ('kiosk', 'Kiosk controller'), ('ambient', 'Ambient / secondary')], default='wall', max_length=10)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('width', models.PositiveIntegerField(default=1920)),
                ('height', models.PositiveIntegerField(default=1080)),
                ('current_panel', models.CharField(blank=True, max_length=120)),
                ('rotation_enabled', models.BooleanField(default=True)),
                ('rotation_seconds', models.PositiveIntegerField(default=45)),
                ('pinned_until', models.DateTimeField(blank=True, help_text='Rotation pauses until this time — the kiosk sets it when someone pins a panel to look at it.', null=True)),
                ('night_mode_start', models.PositiveSmallIntegerField(default=23)),
                ('night_mode_end', models.PositiveSmallIntegerField(default=6)),
                ('brightness', models.PositiveSmallIntegerField(default=100)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DisplayCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('issued_by', models.CharField(blank=True, help_text="Member username, 'kiosk', or 'celery'.", max_length=60)),
                ('delivered', models.BooleanField(default=False)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='displays.display')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
