# Generated by Django 5.2.16 on 2026-08-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='brightness',
        ),
        migrations.RemoveField(
            model_name='display',
            name='current_panel',
        ),
        migrations.RemoveField(
            model_name='display',
            name='night_mode_end',
        ),
        migrations.RemoveField(
            model_name='display',
            name='night_mode_start',
        ),
        migrations.RemoveField(
            model_name='display',
            name='pinned_until',
        ),
        migrations.RemoveField(
            model_name='display',
            name='rotation_enabled',
        ),
        migrations.RemoveField(
            model_name='display',
            name='rotation_seconds',
        ),
    ]
