# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('grace_minutes', models.PositiveIntegerField(default=0, help_text='Time after due before the first rung fires.')),
                ('levels', models.JSONField(default=list)),
                ('stop_on_acknowledge', models.BooleanField(default=True, help_text='Acknowledging the alert halts further rungs.')),
                ('quiet_hours_respected', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'escalation policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('window_ends_at', models.DateTimeField(blank=True, help_text='After this the occurrence is marked missed rather than left open.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_occurrences', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('severity', models.CharField(max_length=10)),
                ('audience', models.CharField(max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('notified', models.ManyToManyField(blank=True, related_name='escalations_received', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tracker.occurrence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('numeric_value', models.FloatField(blank=True, help_text='Reps, minutes, kg, dollars — app decides.', null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='tracker/evidence/%Y/%m/')),
                ('was_skip', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.occurrence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trackable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('task', 'Task'), ('habit', 'Habit'), ('maintenance', 'Maintenance'), ('goal', 'Goal milestone'), ('measurement', 'Measurement'), ('checkin', 'Check-in')], default='task', max_length=15)),
                ('app_slug', models.CharField(db_index=True, default='tracker', help_text='The app that owns this trackable.', max_length=60)),
                ('source_ref', models.CharField(blank=True, db_index=True, help_text="The app's own id for the underlying record.", max_length=120)),
                ('url', models.CharField(blank=True, help_text='Deep link into the owning app.', max_length=300)),
                ('cadence', models.CharField(choices=[('once', 'One time'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('interval', 'Every N days'), ('cron', 'Cron expression')], default='once', max_length=12)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('due_time', models.TimeField(blank=True, help_text='Local time of day an occurrence is due.', null=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requires_evidence', models.BooleanField(default=False, help_text='Completion must include a note, number, or photo.')),
                ('evidence_label', models.CharField(blank=True, max_length=60)),
                ('allow_skip', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_on_wall', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1 high, 2 normal, 3 low.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('escalation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackables', to='tracker.escalationpolicy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'next_due_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='trackable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tracker.trackable'),
        ),
        migrations.AddIndex(
            model_name='trackable',
            index=models.Index(fields=['app_slug', 'source_ref'], name='tracker_tra_app_slu_d4d200_idx'),
        ),
        migrations.AddIndex(
            model_name='trackable',
            index=models.Index(fields=['owner', 'is_active', 'next_due_at'], name='tracker_tra_owner_i_8354eb_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['status', 'due_at'], name='tracker_occ_status_aa34d9_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['status', 'escalation_level', 'due_at'], name='tracker_occ_status_14217e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('trackable', 'due_at')},
        ),
    ]
