# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('why', models.CharField(blank=True, help_text="Shown in the nudge. 'Because my back hurts' works better than 'health'.", max_length=200)),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('weekdays', 'Weekdays'), ('weekly', 'Once a week')], default='daily', max_length=10)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('target_per_week', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
