# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Matches the registered Integration class.')),
                ('name', models.CharField(max_length=80)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('interval_minutes', models.PositiveIntegerField(default=15)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('slug', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
