# Generated by Django 5.2.16 on 2026-08-05 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('colour', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'One time'), ('yearly', 'Every year')], default='none', max_length=6)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_events', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='events', to='todo.label')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('missed', 'Missed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=7)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_completed_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3')])),
                ('source', models.CharField(choices=[('user', 'A person'), ('system', 'Nora Home')], default='user', max_length=6)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('deadline_firm', models.BooleanField(default=False)),
                ('planned_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'One time'), ('fixed', 'Fixed'), ('rolling', 'Rolling')], default='none', max_length=7)),
                ('recurrence_spec', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('open', 'Open'), ('archived', 'Archived'), ('done', 'Done')], db_index=True, default='open', max_length=8)),
                ('escalation_enabled', models.BooleanField(default=False)),
                ('alarm_kind', models.CharField(blank=True, choices=[('chime', 'Chime'), ('file', 'Audio file'), ('speech', 'Spoken text')], max_length=6)),
                ('alarm_ref', models.CharField(blank=True, max_length=300)),
                ('escalation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.escalationpolicy')),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='todo.label')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_minutes', models.IntegerField(blank=True, help_text='Minutes before the due moment. Negative would be after.', null=True)),
                ('absolute_at', models.DateTimeField(blank=True, help_text='Non-recurring tasks only — see the class docstring.', null=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='todo.event')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='todo.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Display text. For an internal path, the real name of what it points at — resolved at render time, not stored stale here.', max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='todo.instance')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='todo.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='todo.task'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_comments', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.instance')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=40)),
                ('from_value', models.JSONField(blank=True, null=True)),
                ('to_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_changes', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='todo.instance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='todo.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='todo/attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_attachments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.event')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.instance')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='todo.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_due_hour', models.PositiveSmallIntegerField(default=9, help_text='Local hour a date-only task falls due, when nothing more specific is set.')),
                ('tone', models.CharField(choices=[('calm', 'Calm'), ('standard', 'Standard'), ('competitive', 'Competitive')], default='standard', max_length=11)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='todo_event_starts__600bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state', 'priority'], name='todo_task_state_1e1992_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source', 'state'], name='todo_task_source_9ca89b_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('task__isnull', False)), models.Q(('event__isnull', False), ('task__isnull', True)), _connector='OR'), name='todo_reminder_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instance__isnull', True), ('task__isnull', False)), models.Q(('instance__isnull', False), ('task__isnull', True)), _connector='OR'), name='todo_link_exactly_one_parent'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['task', 'outcome', 'due_at'], name='todo_instan_task_id_1c61c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instance__isnull', True), ('task__isnull', False)), models.Q(('instance__isnull', False), ('task__isnull', True)), _connector='OR'), name='todo_comment_exactly_one_parent'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['task', 'field', '-created_at'], name='todo_change_task_id_2b217a_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('instance__isnull', True), ('task__isnull', False)), models.Q(('event__isnull', True), ('instance__isnull', False), ('task__isnull', True)), models.Q(('event__isnull', False), ('instance__isnull', True), ('task__isnull', True)), _connector='OR'), name='todo_attachment_exactly_one_parent'),
        ),
    ]
