# Generated by Django 5.2.16 on 2026-08-05 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # The ('tracker', '0001_initial') dependency was dropped by Story 40 along
    # with the tracker app — see the note in 0001_initial. It was only ever here
    # because the autodetector carries an initial migration's dependencies
    # forward; nothing in this file touches an escalation policy.
    dependencies = [
        ('todo', '0002_instance_acknowledged_at_instance_acknowledged_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_approved_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_tasks_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='todo_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instance',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting approval'), ('done', 'Done'), ('missed', 'Missed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=17),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('approver__isnull', True), ('recurrence_type', 'none'), _connector='OR'), name='todo_no_approver_on_recurring'),
        ),
    ]
