# Generated by Django 5.2.16 on 2026-08-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_savedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='todopreference',
            name='tone_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
