# Generated by Django 5.2.17 on 2026-08-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todopreference_tone_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin_ref',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
