# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, help_text='kg, °C, %, ms, USD…', max_length=24)),
                ('app_slug', models.CharField(db_index=True, default='telemetry', max_length=60)),
                ('direction', models.CharField(choices=[('up', 'Higher is better'), ('down', 'Lower is better'), ('range', 'Stay inside a range'), ('neutral', 'Just tracking')], default='neutral', max_length=8)),
                ('warn_below', models.FloatField(blank=True, null=True)),
                ('warn_above', models.FloatField(blank=True, null=True)),
                ('alert_below', models.FloatField(blank=True, null=True)),
                ('alert_above', models.FloatField(blank=True, null=True)),
                ('precision', models.PositiveSmallIntegerField(default=2)),
                ('show_on_wall', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=730, help_text='Raw readings older than this are rolled up and dropped.')),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, help_text='Null for house-wide series.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['app_slug', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='manual | robot | integration | derived', max_length=40)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.series')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['series', '-recorded_at'], name='telemetry_r_series__75946a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HourlyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('mean', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='telemetry.series')),
            ],
            options={
                'ordering': ['-hour'],
                'unique_together': {('series', 'hour')},
            },
        ),
    ]
