# Generated by Django 5.2.16 on 2026-08-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text="Cross-app grouping, e.g. 'health', 'house', 'robot' — lets the home screen group series by theme instead of by which app owns them. Optional; ungrouped series just sort under app_slug.", max_length=40),
        ),
    ]
