# Generated by Django 5.2.16 on 2026-07-31 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surface', models.CharField(choices=[('personal', 'Personal home screen'), ('wall', 'Wall display'), ('shared', 'Shared house screen')], default='personal', max_length=10)),
                ('name', models.CharField(default='Home', max_length=60)),
                ('items', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=True)),
                ('member', models.ForeignKey(blank=True, help_text='Null for shared and wall layouts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surface', 'name'],
                'unique_together': {('member', 'surface', 'name')},
            },
        ),
    ]
